name: home_crm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  stacked: 2.3.3
  sqflite: 2.0.2+1
  path: 1.8.0
  stacked_themes: 0.3.8+1
  google_maps_flutter: ^2.1.1
  get_it: 7.2.0
  intl_phone_field: 3.1.0
  geocoding: 2.0.4
  fluttertoast: 8.0.9
  url_launcher: 6.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

